fetch_articles:
  cron: "0 20 * * 0,4"  # UTC 20時 日曜日(0) 木曜日(4) = JST 5時 月曜日 金曜日
  class: "FetchArticlesJob"
  queue: default

post_daily_19:
  cron: "0 10 * * 1,3"  # UTC 10時 月曜日(1) 水曜日(3) = JST 19時
  class: "PostJob"
  queue: default

post_weekend_12:
  cron: "0 3 * * 6,0"  # UTC 3時 土曜日(6) 日曜日(0) = JST 12時
  class: "PostJob"
  queue: default

post_holiday_12:
  cron: "0 3 * * *"  # UTC 3時 = JST 12時
  class: "PostHolidayJob"
  queue: default
