fetch_articles:
  cron: "0 20 * * 0,4"  # UTC 20:00 日(0),木(4) = JST 5:00 月, 金
  class: "FetchArticlesJob"
  queue: default

post_daily:
  cron: "0 10 * * *"  # UTC 10:00 = JST 19:00
  class: "PostToXJob"
  queue: default

post_weekend:
  cron: "0 3 * * 6,0"  # UTC 3:00 土(6),日(0) = JST 12:00 土, 日
  class: "PostToXJob"
  queue: default

post_national_holiday:
  cron: "0 3 * * 1-5"  # UTC 3:00 月(1)~金(5) = JST 12:00 祝日(土日を除く)
  class: "PostToXJob"
  queue: default

send_gmail:
  cron: "*/10 * * * *"  # 本番環境 動作確認
  # cron: "0 22 * * 5"  # UTC 22:00 金(5) = JST 7:00 土
  class: "SendGmailJob"
  queue: default
